### ISSUE TITLE
Generic guidance and pairing sequence

### ISSUE THREAD

**Issue by cedrox** [McNugget6750/Open-esk8-Remote#3]
Hello @McNugget6750 and thanks for your amazing work. I am really impressing about what you accomplish so far. 
without a doubt, this is the only initiative that seems acceptable to save the acton boards.
Nevertheless, I have several questions:
- Is it possible to have some guidance on the compilation / installation / debugging part?
- Is it possible to emulate your code?
- The pairing phase seems a bit complicated. Is it possible to simplify it?
- Also, do you see a way to recreate an app that allows to skip the pairing phase.

Thank you

**Comment by McNugget6750** [comment]
Hi Cedrox,

Compiling this should be straight forward as I'm not using any external libraries. Just bare Arduino IDE.

Emulation? Hm, never used that on the Arduino. I never deemed it necessary.

Pairing should be as simple as pressing the button but it on the remote and the skateboard. It should be automatic. It's so complex because they designed it this way. It took me a few hours to figure this one out but there is no other way than sending and responding to the needed data from the skateboard. Once paired, the remote just works. In fact, I'm still using mine and the only change I would make is changing the default mode to medium as I'm not riding as fast anymore and increasing the brake performance on the low mode.

Even with an App, the remote needs to be paired. What issues do you see other than that my code appears too complicated?

Cheers,
Timo

**Comment by cedrox** [comment]
Hello @McNugget6750, I don't see any issue. Your code is readable. Due to some comment in the code, I was thinking that there would be a complicated pairing phase... If you are confirming that the pairing phase is easy, that's just great :)
You know, as the app is no more usable neither on iphone or on android, the idea was to use a virtual device on windows for exemple and use the computer as a virtual remote to turn the board in pairing mode (to use acton compatible remote) or to change some parameters... I think there is a real need in the community as today for exemple, it's no more possible to pair a new remote with the board. Please take a look at this video: [How to Re-sync your remote](https://www.youtube.com/watch?v=ERkTwYG-8SM)
Also here to understand more how acton community is frustrated... All those board that cannot be rided anymore...
[Google Play Store terminated "ACTON App" from 2018 for my electric skateboard, what are my options to bypass Log In? : r/hacking](https://www.reddit.com/r/hacking/comments/1f1jgaw/google_play_store_terminated_acton_app_from_2018/?tl=fr)

You know there is a big gap between creating a remote and use a piece of compile software that help you to tweak the settings... 

Thanks for your answer and guidance!

**Comment by McNugget6750** [comment]
I just tested this on my board and my remote pairs with the Acton just fine without the app. The process is the same as described in this video: https://www.youtube.com/watch?v=K_28MCtzsiY

**Bottom line: power on the board. Then wait a few seconds. Then press and hold the board power button for 5-6 seconds. It's now in pairing mode. Then turn on the remote and get the remote into pairing mode. It will pair.**

I would recommend buying and testing one of the remotes suggested in the video. You would be surprised how many boards use the same electronics and Acton is guilty of the same sin. The motor controllers are super cheap mass produced and then (badly) customized units from a Chinese manufacturer who wouldn't give me access to their proprietary configuration software. A real shame they hold this to their chest.

**Comment by McNugget6750** [comment]
I made a quick video about it: https://youtube.com/shorts/J_WrHBChr9Y?si=nbiTlO3fudVXlxiY

**Comment by cedrox** [comment]
Oh super interesting content! Thanks @McNugget6750 
If I follow Thommy drone tech well, you have 2 kinds of ESC, the hobby wing and the LingYi ESC. 
Do you know which one Acton use? If I want to buy a remote, do you know which one will work ?
Thanks for your inputs and advices

**Comment by cedrox** [comment]
FYI I try today to pair acton blink S2 remote on my Acton Qu4tro board with no luck... I have doubt that it can work without the app
Also there is interesting content regarding app just here: https://www.reddit.com/r/hacking/comments/1f1jgaw/google_play_store_terminated_acton_app_from_2018/

sorry as it's a bit out of scope of the initial topic...
Thanks

**Comment by McNugget6750** [comment]
It is very strange. I have tested this on someone else's board that uses the same motor controllers as Acton does. In fact, I have been running into issues with my remote in the distant past and had to switch over to the original one while under way and I don't remember ever using the app for that after I realized how pairing mode works using the power button.

What I don't know is if the Blink S2 uses the same motor controllers!

**Comment by McNugget6750** [comment]
[This](https://www.aliexpress.us/item/3256807400694795.html?src=google&pdp_npi=4%40dis%21USD%2143.08%2139.90%21%21%21%21%21%40%2112000041401118359%21ppc%21%21%21&src=google&albch=shopping&acnt=708-803-3821&isdl=y&slnk=&plac=&mtctp=&albbt=Google_7_shopping&aff_platform=google&aff_short_key=UneMJZVf&gclsrc=aw.ds&albagn=888888&ds_e_adid=&ds_e_matchtype=&ds_e_device=c&ds_e_network=x&ds_e_product_group_id=&ds_e_product_id=en3256807400694795&ds_e_product_merchant_id=5358730274&ds_e_product_country=US&ds_e_product_language=en&ds_e_product_channel=online&ds_e_product_store_id=&ds_url_v=2&albcp=19558607238&albag=&isSmbAutoCall=false&needSmbHouyi=false&gad_source=1&gclid=Cj0KCQiAgJa6BhCOARIsAMiL7V_3hTSMIu_tNrBIzbT7RO4wCYOJpncYXPwfqIOr3YQGc9S56JlXRgUaAs47EALw_wcB&gatewayAdapt=glo2usa) is the same controller that Acton uses in the Qu4tro. If you buy that, the controller should technically pair just fine.

So just to reiterate: I had a spare DIY remote and a friend's kid lost his remote. I was able to pair my spare with his skateboard using this technique and he is still using it. Same ESC for the motor.

**Comment by McNugget6750** [comment]
<img width="527" alt="image" src="https://github.com/user-attachments/assets/52e7f0a5-1840-46a4-90f2-f7f36192fbec">
<img width="437" alt="image" src="https://github.com/user-attachments/assets/d0d6a9e6-68ef-4f46-82f6-502fd9f5efb5">


Yep, same controllers

**Comment by cedrox** [comment]
Thanks for all this precious informations. You rock!  
I try to find the cheapest way to pair an Acton original remote with an Acton skate (as if I follow well all acton remote can go on all acton skateboard) and it seem that the app is still the best way to go. I don't know if there is a generation or hardware difference with your board but I cannot pair with pushing the power button only... I have no possibility to pair the original device without the app... 
FYI my only hope to get the iphone app gone today: https://www.reddit.com/r/hacking/comments/1f1jgaw/google_play_store_terminated_acton_app_from_2018/
Then another question come to my mind: Do you think there is a way to use your code to turn pairing mode on from a normal windows PC with Bluetooth?

**Comment by cedrox** [comment]
Also, it seems that there is quite some logic in https://github.com/McNugget6750/Open-esk8-Remote/blob/master/Pairing_StateMachine.cpp. I am wondering if it could work first on emulator (https://www.etechnophiles.com/best-arduino-simulators/ > https://simulide.com/p/) and then as a built-in windows application? (Console or desktop). It seems that there is a pairing message that is prepared and sent to the transmitter ?
It would save all those dead boards out there :)

**Comment by cedrox** [comment]
Also a question, did you try to link an S2 remote to the qu4tro ? Because in your video you press a button on your custom remote but there is no such button on default Acton remote ? What does this button do ? On default acton remote (s2 at least) you have no way to see if you are in pairing mode. The only button that you have is in the battery case (see below picture) but you don't know if you activate the remote paring state by pressing on it. You also don't know what kind of interaction to do with this button (long press, press after turning on the remote...)
If you follow the official video, you need the app: https://www.youtube.com/watch?v=ERkTwYG-8SM
At min [00:34](https://youtu.be/ERkTwYG-8SM?t=34), he sends a command to the board to be in Re Sync via the app. What is the equivalent on your custom remote ? If we can simulate it with a piece of program, it would be wonderful..

![image](https://github.com/user-attachments/assets/0d7d9b65-56fd-41f5-8cde-905a3c764402)

PS: Also In the official video, his version of the remote have a switch and not a button

**Comment by cedrox** [comment]
Also somebody seems to have found a bit cleverer remote: 
https://www.reddit.com/r/ElectricSkateboarding/comments/1czbk8j/how_do_i_connect_acton_skateboard_with_remote/

**Comment by McNugget6750** [comment]
The Qu4tro remote has a similar button. It's accessible via paper clip from the outside. I believe it has this function but in all fairness, I forgot how it works and I wasn't able to get the remote into pairing mode, either.

The thing is, though: The board DOES! A new remote, once in pairing mode, will pair with the board. The only known (to me) constraint is that the remote needs to be compatible with this type of motor controller.

**Comment by McNugget6750** [comment]
hm, yes these are the correct motor controllers. If you want to give this remote a shot, on a Qu4tro...

https://www.aliexpress.us/item/3256804902020288.html?spm=a2g0o.detail.pcDetailBottomMoreOtherSeller.123.2f8eCM08CM089D&gps-id=pcDetailBottomMoreOtherSeller&scm=1007.40050.354490.0&scm_id=1007.40050.354490.0&scm-url=1007.40050.354490.0&pvid=c8e06f20-40e1-41ef-869b-1cfbf69a7014&_t=gps-id:pcDetailBottomMoreOtherSeller,scm-url:1007.40050.354490.0,pvid:c8e06f20-40e1-41ef-869b-1cfbf69a7014,tpp_buckets:668%232846%238109%231935&pdp_npi=4%40dis%21USD%2197.17%2197.17%21%21%21699.04%21699.04%21%40210318e817329824602142911ec9f2%2112000033913579802%21rec%21US%21169476200%21X&utparam-url=scene%3ApcDetailBottomMoreOtherSeller%7Cquery_from%3A

https://www.aliexpress.us/item/3256807184538171.html?spm=a2g0o.order_list.order_list_main.5.21ef5e5bFg5LpV&gatewayAdapt=fra2usa4itemAdapt#nav-store

**Comment by cedrox** [comment]
> hm, yes these are the correct motor controllers. If you want to give this remote a shot, on a Qu4tro...
> 
> https://www.aliexpress.us/item/3256804902020288.html?spm=a2g0o.detail.pcDetailBottomMoreOtherSeller.123.2f8eCM08CM089D&gps-id=pcDetailBottomMoreOtherSeller&scm=1007.40050.354490.0&scm_id=1007.40050.354490.0&scm-url=1007.40050.354490.0&pvid=c8e06f20-40e1-41ef-869b-1cfbf69a7014&_t=gps-id:pcDetailBottomMoreOtherSeller,scm-url:1007.40050.354490.0,pvid:c8e06f20-40e1-41ef-869b-1cfbf69a7014,tpp_buckets:668%232846%238109%231935&pdp_npi=4%40dis%21USD%2197.17%2197.17%21%21%21699.04%21699.04%21%40210318e817329824602142911ec9f2%2112000033913579802%21rec%21US%21169476200%21X&utparam-url=scene%3ApcDetailBottomMoreOtherSeller%7Cquery_from%3A
> 
> https://www.aliexpress.us/item/3256807184538171.html?spm=a2g0o.order_list.order_list_main.5.21ef5e5bFg5LpV&gatewayAdapt=fra2usa4itemAdapt#nav-store

I ordered 2 different models. I will keep you posted ;)

**Comment by cedrox** [comment]
> The Qu4tro remote has a similar button. It's accessible via paper clip from the outside. I believe it has this function but in all fairness, I forgot how it works and I wasn't able to get the remote into pairing mode, either.
> 
> The thing is, though: The board DOES! A new remote, once in pairing mode, will pair with the board. The only known (to me) constraint is that the remote needs to be compatible with this type of motor controller.


Then it seems that the app is mandatory in the process... As you bypass this constraint in your custom build, it means that your remote should send something to the board that the original remote does not?

**Comment by cedrox** [comment]
This [model ](https://fr.aliexpress.com/item/1005004939794906.html?spm=a2g0o.order_list.order_list_main.11.41405e5bPS4uwg&gatewayAdapt=glo2fra) is working with the Qu4tro.

Not managed yet to get it work on the Acton blink S2

**Comment by McNugget6750** [comment]
I am very happy to hear that at least the Qu4tro works again!
That should also confirm that the pairing mechanism is actually working on the Qu4tro.

**Comment by cedrox** [comment]
It was a pleasure chatting with you. Hope that this thread will help a bit
